### PR TITLE
Updated puff.py

### PR DESCRIPTION
**Pull request by yimingli**
post() takes more arguments.

### CODE REVIEW

**Comment by juzam** [comment]
post() takes more arguments but after a quick glance at the code they are derived inside the function here:

```
        self.br['bookmark[url]'] = url
        self.br['bookmark[title]'] = title
        self.br['bookmark[description]'] = description
```

**Comment by yimingli** [comment]
I don't really know python. I edited it based on the error message I got. It says post() takes 4 arguments, and only 2 is given. So I added 'title' and 'description', now it works. Maybe it's just a coincidence on my computer.

**Comment by juzam** [comment]
Ha! I'm sorry I didn't see it before but now I know what's going on:

```
if __name__ == '__main__':
    try:
        url = sys.argv[1]
        title = sys.argv[2]
        description = sys.argv[3]
    except:
        print 'Please specify a url to Puff, title and description'
        exit()
```

this was the block giving you the error it basically says that you need to provide 3 arguments via command line (if you're using the script via CLI of course).
after failing (if you don't provide all the parameters) it goes on and calls post() with just one parameter.

```
    puffer = Puffer()
    puffer.post(url)
```

So It's sane to have all the parameters in the call afterwards.

I'll merge the patch after doing some tests.

(please note that I'm not the one who wrote the utility in the first place)

**Comment by yimingli** [comment]
Yeah I noticed that. The original script did not have title and description. I see that you added these two very useful information. I'm glad you did!

By the way, I'm also using your excellent bash script (https://gist.github.com/juzam/8004696) to automate the whole process. I guess that's why I only provided 'url', because your script automatically grab the title and the description.

**Comment by juzam** [comment]
Merged, thanks!

**Pull request merged**
